Q1. WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR
ANNUAL SALARY

1.SELECT ENAME,SAL*12
    FROM EMP
    

Q2. WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE WITH
THEIR HALF TERM SALARY.

2.SELECT ENAME,SAL*12
   FROM EMP;
 
Q3. WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG
WITH AN ANNUAL BONUS OF 2000.

  3.SELECT EMP.*,(SAL*12)+2000
   FROM EMP;

Q4. WAQTD NAME SALARY AND SALARY WITH A HIKE OF
10%

  4.SELECT ENAME,SAL,SAL+SAL*10/100
   FROM EMP;

Q5. WAQTD NAME AND SALARY WITH DEDUCTION OF 25%.

  5.SELECT ENAME,SAL-SAL*25/100
   FROM EMP;

Q6. WAQTD NAME AND SALARY WITH MONTHLY HIKE OF
50

  6. SELECT ENAME,SAL+50,(SAL+50)
   FROM EMP;

Q7. WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION
OF 10%.

   7.SELECT ENAME,(SAL*12)-(SAL*12)*(1/10)
    FROM EMP;


Q8. WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE
(SAL+COMM).

  8.SELECT EMP.*,(SAL+COMM)
  FROM EMP;


Q9.WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH
ANNUAL SALARY

  9.SELECT EMP.*,(SAL*12)
   FROM EMP;


Q10. WAQTD NAME AND DESIGNATION ALONG WITH 100
PENALTY IN SALARY.

  10.SELECT ENAME,JOB,(SAL-100)
   FROM EMP;




