1.WAQTD NAMES OF THE EMPLOYEES EARNING MORE
THAN SCOTT IN ACCOUNTING DEPT.

1. SELECT ENAME
FROM EMP
WHERE SAL>(SELECT SAL
FROM EMP
WHERE ENAME='SCOTT') AND DEPTNO=(SELECT DEPTNO
FROM DEPT
WHERE DNAME='ACCOUNTING');



2.WAQTD DETAILS OF THE EMPLOYEES WORKING AS
MANAGER IN THE LOCATION CHICAGO.

2. SELECT * FROM EMP
 WHERE JOB IN 'MANAGER' AND DEPTNO IN(SELECT DEPTNO FROM DEPT 
WHERE LOC='CHICAGO');

3.WAQTD NAME AND SAL OF THE EMPLOYEES EARNING
MORE THAN KING IN THE DEPT ACCOUNTING.

3.  SELECT ENAME,SAL
 FROM EMP
 WHERE SAL>(SELECT SAL
 FROM EMP
 WHERE ENAME='KING') AND DEPTNO=(SELECT DEPTNO
 FROM DEPT
 WHERE DNAME='ACCOUNTING');

4.WAQTD DETAILS OF THE EMPLOYEES WORKING AS
SALESMAN IN THE DEPARTEMENT SALES.

4.SELECT ENAME
FROM EMP
WHERE JOB='SALESMAN' AND DEPTNO=(SELECT DEPTNO
FROM DEPT 
WHERE DNAME='SALES');

5.WAQTD NAME , SAL , JOB , HIREDATE OF THE EMPLOYEES
WORKING IN OPERATIONS DEPARTMENT AND HIRED
BEFORE KING.

5.SELECT ENAME,SAL,JOB,HIREDATE
 FROM EMP
WHERE HIREDATE<(SELECT HIREDATE
FROM EMP
WHERE ENAME='KING') AND DEPTNO=(SELECT DEPTNO
FROM DEPT
WHERE DNAME='OPERATIONS');

6.DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET
NAMES ENDING 'S'.

6. SELECT *
FROM EMP
 WHERE DEPTNO IN (SELECT DEPTNO
FROM DEPT
 WHERE DNAME  LIKE '%S');

7.WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS
CHARACTER 'A' IN IT .

7.SELECT *
FROM DEPT
WHERE DEPTNO IN(SELECT DEPTNO
FROM EMP
WHERE ENAME LIKE'%A%');

8.WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS
SALARY IS RUPEES 800 .

8.SELECT DNAME,LOC
 FROM DEPT
 WHERE DEPTNO IN(SELECT DEPTNO
 FROM EMP
 WHERE SAL=800);

9.WAQTD DNAME OF THE EMPLOYEES WHO EARN
COMISSION.

 9.  SELECT *
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
  FROM EMP
  WHERE COMM IS NOT NULL);

10.WAQTD LOC OF THE EMPLOYEES IF THEY EARN
COMISSION IN DEPT 40.

10.SELECT LOC
 FROM DEPT
 WHERE DEPTNO =40 AND DEPTNO IN (SELECT DEPTNO
  FROM EMP

  WHERE COMM IS NOT NULL);

