1.WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS
SMITH.

1.SELECT DNAME
 FROM DEPT
  WHERE DEPTNO=(SELECT DEPTNO
  FROM EMP
  WHERE ENAME='SMITH');

2.WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS
ENAME IS KING 
  
2.SELECT DNAME,LOC
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE ENAME='KING');

3.WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS
7902.

3.SELECT *
 FROM DEPT
 WHERE DEPTNO=(SELECT DEPTNO
 FROM EMP
 WHERE EMPNO='7902');

4.WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE
EMPLOYEE WHOS NAME ENDS WITH 'R'.

4.SELECT DNAME,LOC,DEPTNO
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE ENAME IN '%R%');

5.WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION
IS PRESIDENT.

5.SELECT DNAME
 FROM DEPT
 WHERE DEPTNO=(SELECT DEPTNO
 FROM EMP
 WHERE JOB='PRESIDENT');

6.WAQTD NAMES OF THE EMPLOYEES WORKING IN
ACCOUNTING DEPARTMENT.

6.SELECT ENAME
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO
FROM DEPT
WHERE DNAME='ACCOUNTING');

7.WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO
ARE WORKING IN THE LOCATION CHICAGO.

7.  SELECT ENAME,SAL
 FROM EMP
  WHERE DEPTNO=(SELECT DEPTNO
  FROM DEPT
  WHERE LOC='CHICAGO');

8.WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES

8.SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
 FROM DEPT
 WHERE JOB='SALES');

9..WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL
SALARY IF EMPLOYEES ARE WORKING IN NEW YORK

9. SET LINES 100 PAGES 100;
SELECT EMP.*,(SAL*12) ANNUSAL
 FROM EMP
 WHERE DEPTNO=(SELECT DEPTNO
 FROM DEPT
 WHERE LOC='NEW YORK');

10..WAQTD NAMES OF EMPLOYEES WORKING IN
OPERATIONS DEPARTMENT

10.SELECT ENAME
  FROM EMP
  WHERE DEPTNO=(SELECT DEPTNO
 FROM DEPT
 WHERE DNAME='OPERATIONS');