1.WAQTD SMITHS REPORTING MANAGER'S NAME.

1. SELECT ENAME
 FROM EMP
 WHERE EMPNO=(SELECT MGR
 FROM EMP
 WHERE ENAME='SMITH');

2.WAQTD ADAMS MANAGER'S MANAGER NAME 
 
2.SELECT ENAME
FROM EMP
WHERE EMPNO=(SELECT MGR
FROM EMP
WHERE EMPNO=(SELECT MGR
FROM EMP
WHERE ENAME='ADAMS'));

3.WAQTD DNAME OF JONES MANAGER

3.SELECT DNAME
FROM DEPT
 WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE EMPNO=(SELECT MGR
FROM EMP
WHERE ENAME='JONES'));

4.WAQTD MILLER'S MANAGER'S SALARY

4.SELECT SAL
FROM EMP
WHERE EMPNO=(SELECT MGR 
FROM EMP
WHERE ENAME='MILLER');

5.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.

5.SELECT LOC
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE EMPNO=(SELECT MGR
FROM EMP
WHERE ENAME='SMITH'));

6.WAQTD NAME OF THE EMPLOYEES REPORTING TO
BLAKE 

6.SELECT ENAME
FROM EMP
WHERE MGR=(SELECT EMPNO
FROM EMP
WHERE ENAME='BLAKE');

77.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING

7.SELECT COUNT(ENAME)
 FROM EMP
 WHERE MGR=(SELECT EMPNO
 FROM EMP
 WHERE ENAME='KING');

8.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO
JONES.

8.  SELECT *
 FROM EMP
 WHERE MGR=(SELECT EMPNO
 FROM EMP
 WHERE ENAME='JONES');

9.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO
BLAKE'S MANAGER.

9. SELECT ENAME
 FROM EMP
 WHERE MGR=(SELECT MGR
 FROM EMP
 WHERE ENAME='BLAKE');

0.WAQTD NUMBER OF EMPLOYEES REPORTING TO FORD'S
MANAGER.

10.SELECT COUNT(*)
FROM EMP
WHERE MGR=(SELECT MGR
FROM EMP
WHERE ENAME='FORD');
