Q1.WAQTD DETAILS OF THE EMPLOYEES WORKING
AS CLERK AND EARNING LESS THAN 1500

1. SELECT *
FROM EMP
WHERE JOB='CLERK'
AND SAL < 1500;

Q2.WAQTD NAME AND HIREDATE OF THE EMPLOYEES
WORKING AS MANAGER IN DEPT 30.

2.SELECT ENAME,HIREDATE
 FROM EMP
 WHERE JOB='MANAGER'
 AND DEPTNO=30;

Q3.WAQTD DETAILS OF THE EMP ALONG WITH
ANNUAL SALARY IF THEY ARE WORKING IN DEPT
30 AS SALESMAN AND THEIR ANNUAL SALARY HAS
TO BE GREATER THAN 14000.

3.SELECT ENAME,JOB DEPTNO,SAL,SAL*12
 FROM EMP
 WHERE DEPTNO=30
 AND JOB='SALESMAN';

                            OR

SELECT EMP.*,SAL*12
FROM EMP
WHERE DEPTNO=30 AND JOB='SALESMAN' AND SAL*12 > 12000;

Q4.WAQTD ALL THE DETAILS OF THE EMP WORKING
IN DEPT 30 OR AS ANALYST.

4.SELECT *
 FROM EMP
 WHERE DEPTNO = 30
OR JOB = 'ANALYST';

Q5.WAQTD NAMES OF THE EMPMLOYEES WHOS
SALARY IS LESS THAN 1100 AND THEIR
DESIGNATION IS CLERK.

5. SELECT *
FROM EMP
WHERE SAL < 1100
AND JOB = 'CLERK';

Q6.WAQTD NAME AND SAL , ANNUAL SAL AND
DEPTNO IF DEPTNO IS 20 EARNING MORE THAN 1100
AND ANNUAL SALARY EXCEEDS 12000.

6.SELECT ENAME,SAL,(SAL*12) DEPTNO
FROM EMP
WHERE DEPTNO=20 AND SAL>1100 AND SAL*12 >12000;

Q7.WAQTD EMPNO AND NAMES OF THE EMPLOYEES
WORKING AS MANAGER IN DEPT 20.

7.SELECT EMPNO,ENAME
FROM EMP
WHERE JOB ='MANAGER'
AND DEPTNO=20;

Q8.WAQTD DETAILS OF EMPLOYEES WORKING IN
DEPT 20 OR 30.

8.SELECT *
FROM EMP
WHERE DEPTNO=20
OR DEPTNO=30;

Q9.WAQTD DETAILS OF EMPLOYEES WORKING AS
ANALYST IN DEPT 10 

9.SELECT *
 FROM EMP
 WHERE DEPTNO=10
 AND JOB='ANALYST';
                  
FOR OR

SELECT *
FROM EMP
WHERE DEPTNO=10
OR JOB = 'ANALYST';

Q10.WAQTD DETAILS OF EMPLOYEE WORKING AS
PRESIDENT WITH SALARY OF RUPEES 4000.

10.SELECT *
 FROM EMP
 WHERE JOB = 'PRESIDENT'
 AND SAL = 4000;

Q11.WAQTD NAMES AND DEPTNO , JOB OF EMPS
WORKING AS CLERK IN DEPT 10 OR 20.

11.SELECT ENAME,DEPTNO
FROM EMP
WHERE JOB ='CLERK'
AND (DEPTNO=10 OR DEPTNO=20);

                  OR

SELECT ENAME,DEPTNO
 FROM EMP
 WHERE JOB ='CLERK'
AND DEPTNO=10
OR DEPTNO=20;

Q12.WAQTD DETAILS OF EMPLOYEES WORKING AS
CLERK OR MANAGER IN DEPT 10 .

12.SELECT *
 FROM EMP
 WHERE DEPTNO = 10
 AND JOB ='CLERK'
OR JOB='MANAGER';

Q13.WAQTD NAMES OF EMPLOYEES WORKING IN
DEPT 10 , 20 , 30 , 40 .

13.SELECT ENAME
 FROM EMP
 WHERE DEPTNO IN (10,20,30,40);

Q14.WAQTD DETAILS OF EMPLOYEES WITH EMPNO
7902,7839.

14. SELECT *
FROM EMP
WHERE EMPNO IN (7902,7839);

Q15.WAQTD DETAILS OF EMPLOYEES WORKING AS
MANAGER OR SALESMAN OR CLERK

15.SELECT *
 FROM EMP
 WHERE JOB IN ('MANAGER','SALESMAN','CLERK');

Q16.WAQTD NAMES OF EMPLOYEES HIRED AFTER 81
AND BEFORE 87.

16.SELECT ENAME,HIREDATE
 FROM EMP
 WHERE HIREDATE > '31-DEC-81'
 AND HIREDATE < '01-JAN-87';

17.WAQTD DETAILS OF EMPLOYEES EARNING MORE
THAN 1250 BUT LESS THAN 3000

17.SELECT *
FROM EMP
WHERE SAL > 1250
AND SAL < 3000;

Q18.WAQTD NAMES OF EMPLOYEES HIRED AFTER 81
INTO DEPT 10 OR 30 .

18.SELECT ENAME, HIREDATE, DEPTNO
FROM EMP
WHERE HIREDATE > '31-DEC-81'
AND DEPTNO IN (10,30);

Q19.WAQTD NAMES OF EMPLOYEES ALONG WITH
ANNUAL SALARY FOR THE EMPLOYEES WORKING
AS MANAGER OR CLERK INTO DEPT 10 OR 30.

19.SELECT ENAME ,(SAL*12) AS ANNUALSAL
  FROM EMP
  WHERE JOB IN('MANAGER','CLERK')
  AND DEPTNO IN (10,30);

20.WAQTD ALL THE DETAILS ALONG WITH ANNUAL
SALARY IF SAL IS BETWEEN 1000 AND 4000 ANNUAL
SALARY MORE THAN 15000.


20.SELECT EMP.*,  (SAL*12) AS ANNUALSAL
 FROM EMP
 WHERE SAL BETWEEN 1000 AND 4000
 AND (SAL * 12) > 15000;

