1.WAQTD NAME OF THE EMPLOYEE EARNING MAXIMUM
SALARY.

1. SELECT ENAME
 FROM EMP
 WHERE SAL=(SELECT MAX(SAL)
 FROM EMP);

2.WAQTD NAME OF THE EMPLOYEE EARNING MINIMUM
SALARY.

2.  SELECT ENAME
 FROM EMP
 WHERE SAL=(SELECT MIN(SAL)
 FROM EMP);

3.WAQTD NAME AND HIREDATE OF THE EMPLOYEE HIRED
BEFORE
ALL THE EMPLOYEES (FIRST EMP).

3. SELECT ENAME,HIREDATE
FROM EMP
 WHERE HIREDATE=(SELECT MIN(HIREDATE)
FROM EMP);

4.WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED
AT THE LAST.

 
4. SELECT ENAME,HIREDATE
 FROM EMP
  WHERE HIREDATE=(SELECT MAX(HIREDATE)
  FROM EMP);

5.WAQTD NAME, COMM OF THE EMPLOYEE WHO EARNS
MIN COMISSION.

5. SELECT ENAME,HIREDATE
FROM EMP
 WHERE HIREDATE=(SELECT MIN(HIREDATE)
FROM EMP);

6.WAQTD NAME, SAL AND COMM OF THE EMPLOYEE
EARNING MAXIMUM
COMISSION .


6. SELECT ENAME,COMM
 FROM EMP
 WHERE COMM=(SELECT MAX(COMM)
 FROM EMP);

7.WAQTD DETAILS OF THE EMPLOYEE WHO HAS GREATEST
EMPNO .

7. SELECT *
FROM EMP
WHERE EMPNO=(SELECT MAX(EMPNO)
FROM EMP);

8.WAQTD DETAILS OF THE EMPLOYEES HAVING THE LEAST
HIREDATE.

8.SELECT *
FROM EMP
WHERE EMPNO=(SELECT MIN(EMPNO)
 FROM EMP);

9.WAQTD DETAILS OF THE EMPLOYEES EARNING LEAST
ANNUAL SALARY.

9. SELECT *
FROM EMP
WHERE (SAL*12)=(SELECT MIN(SAL*12)
FROM EMP);

10.WAQTD NAME , ANNUAL SALARY OF THE EMPLOYEES IF
THEIR ANNUAL SALARY IS MORE THAN ALL THE SALESMAN.

10. SELECT ENAME,(SAL*12)
 FROM EMP
WHERE (SAL*12)>(SELECT MAX(SAL*12)
 FROM EMP
WHERE JOB='SALESMAN');