1.WAQTD 2ND MINIMUM SALARY

1.SELECT MIN(SAL)
FROM EMP
WHERE SAL >(SELECT MIN(SAL)
FROM EMP);

2.WAQTD 5TH MAXIMUM SALARY

2.SELECT MAX(SAL)
FROM EMP
WHERE SAL <(SELECT MAX(SAL)
FROM EMP
WHERE SAL <(SELECT MAX(SAL)
 FROM EMP
WHERE SAL <(SELECT MAX(SAL)
FROM EMP
WHERE SAL <(SELECT MAX(SAL)
FROM EMP))));

3.WAQTD NAME OF THE EMPLOYEE EARNING 3RD
MAXIMUM SALARY.

3.SELECT ENAME
FROM EMP
WHERE SAL=(SELECT MAX(SAL)
FROM EMP
  WHERE SAL <(SELECT MAX(SAL)
  FROM EMP
  WHERE SAL <(SELECT MAX(SAL)
  FROM EMP)));

4.WAQTD EMPNO OF THE EMPLOYEE EARNING 2D
MAXIMUM SALARY 

4.SELECT EMPNO
 FROM EMP
 WHERE SAL=(SELECT MAX(SAL)
 FROM EMP
 WHERE SAL<(SELECT MAX(SAL)
 FROM EMP));

5.WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING
4TH MAX SAL

5.SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE SAL=(SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL)
FROM EMP)))));

6.WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd

6. SELECT *
 FROM EMP
 WHERE HIREDATE=(SELECT MIN(HIREDATE)
 FROM EMP
 WHERE HIREDATE>(SELECT MIN(HIREDATE)
 FROM EMP));

7.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE
LAST EMPLOYEE

7.SELECT ENAME
FROM EMP
WHERE HIREDATE>(SELECT MIN(HIREDATE)
FROM EMP);

8.WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST.

8.SELECT LOC
 FROM DEPT
 WHERE DEPTNO = (SELECT DEPTNO
 FROM EMP
 WHERE HIREDATE=(SELECT MIN(HIREDATE)
 FROM EMP));

9.WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH
MINIMUM SALARY.

9.SELECT *
 FROM EMP
 WHERE SAL=(SELECT MIN(SAL)
 FROM EMP
 WHERE SAL>(SELECT MIN(SAL)
 FROM EMP
 WHERE SAL>(SELECT MIN(SAL)
 FROM EMP
 WHERE SAL>(SELECT MIN(SAL)
 FROM EMP
 WHERE SAL>(SELECT MIN(SAL)
 FROM EMP
 WHERE SAL>(SELECT MIN(SAL)
 FROM EMP
 WHERE SAL>(SELECT MIN(SAL)
 FROM EMP)))))));

10.WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM
SALARY

10.SELECT DNAME
  FROM DEPT
  WHERE DEPTNO IN (SELECT DEPTNO
 FROM EMP
 WHERE SAL=(SELECT MAX(SAL)
 FROM EMP
 WHERE SAL<(SELECT MAX(SAL)
 FROM EMP)));