1.WAQTD NAME OF THE EMPLOYEES EARNING SALARY
MORE THAN THE SALESMAN.

1.SELECT ENAME
FROM EMP
WHERE SAL>ALL(SELECT SAL
FROM EMP
WHERE JOB='SALESMAN');

2.WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL
THE CLERKS.

2. SELECT *
 FROM EMP
 WHERE HIREDATE>ALL(SELECT HIREDATE
 FROM EMP
 WHERE JOB='CLERKS');

3.WAQTD NAME AND SALARY FOR ALL THE EMPLOYEES IF
THEY ARE EARNING LESS THAN ATLEST A MANAGER.

3.SELECT ENAME,SAL
FROM EMP
WHERE SAL<ANY(SELECT SAL
FROM EMP
WHERE JOB IN 'MANAGER');

4.WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED
BEFORE ALL THE MANAGERS.

4.SELECT ENAME,HIREDATE
 FROM EMP
 WHERE HIREDATE>ALL(SELECT HIREDATE
 FROM EMP
 WHERE JOB IN 'MANAGER');

5.WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL
THE MANAGERS AND EARNING SALARY MORE THAN ALL
THE CLERKS.

5.SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE>ALL(SELECT HIREDATE
FROM EMP
 WHERE JOB IN 'MANAGER') AND SAL>ALL(SELECT SAL
FROM EMP
WHERE JOB IN 'CLERKS');

6.WAQTD DETAILS OF THE EMPLOYEES WORKING AS
CLERK AND HIRED BEFORE ATLEST A SALESMAN.

6.SELECT *
FROM EMP
WHERE JOB IN 'CLERK' AND HIREDATE<ANY(SELECT HIREDATE
FROM EMP
WHERE JOB IN 'SALESMAN');

7.WAQTD DETAILS OF EMPLOYEES WORKING IN
ACCOUNTING OR SALES DEPT.

7. SELECT *
 FROM EMP
 WHERE DEPTNO IN (SELECT DEPTNO
FROM DEPT
 WHERE DNAME IN ('ACCOUNTING','SALES'));

8.WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH
NAME SMITH , KING AND MILLER.

8. SELECT DISTINCT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
FROM EMP
WHERE ENAME IN('SMITH','KING','MILLER'));

9.WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK
OR CHICAGO.

9.SELECT ENAME
FROM EMP
WHERE DEPTNO IN(SELECT DEPTNO
FROM DEPT
WHERE LOC IN ('NEWYORK','CHICAGO'));

10.WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER
ALL THE EMPLOYEES OF DEPT 10.

10.SELECT ENAME 
FROM EMP
WHERE HIREDATE>ALL (SELECT HIREDATE 
FROM EMP
WHERE DEPTNO=10);